# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - postgres
  centos:
    image: centos
    networks:
      - postgres
networks:
  postgres:
    driver: bridge